Gopkg.lock
build/build.sh
cmd/goldpinger/main.go
pkg/goldpinger/stats.go

There is no longer need to return the manually counted metrics in the ping response, since metrics are covering that. Plus, that was not thread-safe.
I'm leaving the swagger spec as is for backwards compatibility.

Simplify and fix ping response, add build info during build time

---

pkg/goldpinger/config.go
pkg/goldpinger/k8s.go

This allows an operator to set the `LABEL_SELECTOR` environment variable to configure discovery of goldpinger Pods

Use a configuration value for the label selector when discovering goldpinger pods

---

.dockerignore
Dockerfile
Makefile

*why?*
The current Dockerfile fetches source code using `go get` which will always download `master` branch by default. 
It's probably not what you intended when building from specific git tag/sha.

fix Dockerfile to build from current workspace

---

.travis.yml
Makefile
build/build.sh

Fixes #17 
In this PR:
- Added a possibility to pass `GOOS` to `build.sh` (as an environment variable);
- Changed `make build` workflow to:
- Remove previous binary (the name of binary is hardcoded, because it's also hardcoded in `Dockerfile-simple`);
- Compile a new binary with `GOOS=linux`;
- Run docker build.

Fix GOOS problems during simple docker build

---

extras/example-serviceaccounts.yml

Here is a better version of https://github.com/bloomberg/goldpinger/blob/master/extras/example-serviceaccounts.yml
I just can't make it turn key because of https://github.com/bloomberg/goldpinger/issues/27
other than that, one can simply `kubectl apply -f example-serviceaccounts.yml` and have goldpinger running out of the box.
To remove it, one should type `kubectl delete -f example-serviceaccounts.yml`

More complete example-serviceaccounts.yml, now with rbac rules

---

README.md

the extra 'y' will cause the Prometheus Rule never to fire.

fix README.md to point to right metric for AlertManager example

---

Gopkg.lock
Makefile
build/Dockerfile-simple
pkg/goldpinger/heatmap.go
pkg/restapi/configure_goldpinger.go
static/index.html

This PR attempts to add a heatmap functionality inspired by [Pingmesh paper](https://conferences.sigcomm.org/sigcomm/2015/pdf/papers/p139.pdf) (see page 150 for some examples) and initially suggested by @[thegedge](/thegedge) in https://github.com/bloomberg/goldpinger/issues/43.
I wanted to see if this could be easily done with the Go image library, so that the image can be saved, shared, etc.
On my little test cluster, it currently looks like this:
Note: This is still very much an experiment.
Resolves https://github.com/bloomberg/goldpinger/issues/43

Add heatmap

---

.travis.yml
Makefile
docker_deploy.sh

This patch will enable pushes of any successful builds (using Travis-CI)
of the 'master' branch to the proper repository on DockerHub. The credentials
necessary are provided via environment variables configured in the
Travis-CI settings.
Addresses issue #27
Signed-off-by: Kevin P. Fleming <kpfleming@bloomberg.net>

Enable push of images to DockerHub

---

Gopkg.lock
Gopkg.toml
Makefile
README.md
cmd/goldpinger/main.go
extras/example-serviceaccounts.yml
extras/example-with-kubeconfig.yaml
pkg/goldpinger/client.go
pkg/goldpinger/config.go
pkg/goldpinger/pod_selecter.go
pkg/goldpinger/updater.go
pkg/restapi/configure_goldpinger.go
static/index.html

Select a user-defined number of pods via
rendezvous hash. This is important for larger
clusters, where the metric cardinality explosion
is too much for a single prometheus to handle.
discussed in https://github.com/bloomberg/goldpinger/issues/52

Add rendezvous hash for selecting subset of nodes

---

README.md

*#1*
goldPinger expose prometheus metrics at ip:port/metrics, and you need to send it to prometheus or add configuration to prometheus in order to fetch, but if this request merged, you will allow prometheus to auto-discover your metrics and fetch it from service-name:ip/metrics 
I add this and checked from prometheus side if target is up and metrics fetched.
Add any other context about your contribution here.

prometheus service auto-discovery  

---

Makefile
README.md
pkg/goldpinger/client.go

If you run into a situation where kubernetes returns one of the goldpinger nodes without an IP (say, for example, that docker went rogue and is stuck trying to start the pod):
```sh
$ kubectl get pods | grep goldpinger
goldpinger-2n2lc                1/1     Running     0          18m   10.244.50.82    my-cluster-master-2   <none>           <none>
goldpinger-9jg79                1/1     Running     0          23m   10.244.68.120   my-cluster-worker-1   <none>           <none>
goldpinger-hvk6q                0/1     Completed   0          37m   <none>          my-cluster-worker-0   <none>           <none>
goldpinger-l4hkl                1/1     Running     0          18m   10.244.34.82    my-cluster-master-1   <none>           <none>
goldpinger-vspx7                1/1     Running     0 …
```

Fix a Goldpinger reporting healthy when kubernetes returns an empty IP field

---

pkg/goldpinger/client.go
pkg/goldpinger/config.go
pkg/goldpinger/pinger.go
pkg/goldpinger/updater.go
pkg/models/pod_result.go
pkg/restapi/embedded_spec.go
swagger.yml

We recently added alerts for more than 30% of our goldpinger pods taking more than 50ms to respond to ping requests and we started getting lots of alerts from *all* our nodes in multiple clusters with > 50 nodes. This was a surprise since it should *NOT* take 50 milliseconds for goldpinger to send a very simple HTTP request and get a response. 
Digging deeper by clicking on a heatmap, things look really bad:
Most nodes seem to be taking over `100ms` to respond. After ruling out some form of connection pooling/network throttling, we came to the conclusion that goldpinger was being CPU starved since we had set the CPU requests to 0.05 CPU cores and the limit to 0.1 CPU cores. To check if that was an issue, I manually created a cgroup for goldpinger and ran it locally:
```sh
sudo yum install …
```

Calm the thundering herd

---

cmd/goldpinger/main.go
pkg/goldpinger/config.go
pkg/goldpinger/k8s.go

Adds a configuration option to allow for cross-namespace pings.
Our intention is to mainly use `''` ("all namespaces") to handle connectivity probing between namespace-scoped things (network policies, policy-driven webhooks, etc.). I also expect that setting the value to a namespace other than the one containing the pod ran in something of an "query only" mode, in that it aggregates results without showing up in the others' ping targets.
I ran Goldpinger pods both with and without the new configuration: without, the pod successfully discovered itself in its own namespace (nothing else was running there), and with the value set to `''` they successfully discovered each other across a namespace boundary.
The …

feat: configurable namespace for pod discovery

---

.github/workflows/publish.yml
Dockerfile
Makefile
README.md
build/build.sh
docker_deploy.sh
go.mod

*Issue number of the reported bug or feature request: #94*
This does a multi-stage, multi-architecture build for goldpinger.
Docker build, pushed to internal repository, ran in kubernetes, verified metrics available.
@seeker89 mentioned that they'll be moving to GH actions so I included an example setup of the action to build & publish on new tags. GH action hasn't been fully tested for the `-vendor` builds.

[WORK IN PROGRESS] Multi-architecture builds for goldpinger

---

pkg/goldpinger/config.go
pkg/goldpinger/k8s.go

*Issue number of the reported bug or feature request: #<number>*
I changed `pod.Name` to `p.Spec.NodeName`, so we can see the nodename other than podname in the UI.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.
goldpinger is deployed by daemonset, so nodename is better than podname.

Display hostName other than podName

---

pkg/goldpinger/updater.go

*Issue number of the reported bug or feature request: #<number>*
A clear and concise description of the changes you have made.
heatmap will be broken in every refeshPeriod,
I found pinger is be deleted because of exists check faild.
updatePingers will check if a pod still exist or a new one,
and update pingers in every refreshPeriod.
the function exists failed to check pod exist, so fix it.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.

Fix pinger be removed by not found.

---

cmd/goldpinger/main.go

CI for https://github.com/bloomberg/goldpinger/pull/115 failed of a missing an import in main.go: 
https://github.com/bloomberg/goldpinger/runs/8043769389?check_suite_focus=true
Apologies I must have made a mistake when rebasing.
Signed-off-by: kitfoman <thaddeusgetachew@gmail.com>

[Bug Fix] add missing dependency

---

Dockerfile
Makefile
cmd/goldpinger/main.go
config/zap.json
pkg/goldpinger/config.go

*Issue number of the reported bug or feature request: #123 *
1. Removed the nasty `DEBUG` environment variable that is loaded outside of swagger's parser.
2. Added a command line argument `--zap-config` that points to a valid json zap config file
3. Added a `/config` folder to store the zap config file
4. Added a default zap config file under `config/zap.json`
Loaded different zap configuration files such as `zap.prod.json`, `zap.dev.json` to test that the log level and outputPaths are the correct ones.

feat: support advanced zap configuration

---

README.md
extras/example-serviceaccounts.yml

This commit updates the README and examples to use rbac.authorization.k8s.io/v1, which has been available since K8s 1.8
rbac.authorization.k8s.io/v1beta1 was deprecated in K8s 1.17 and removed in K8s 1.22.
Used `kubectl apply` with the updated manifests from the README in a K8s cluster running 1.23.
Deprecation notice: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122

Remove deprecated rbac.authorization.k8s.io/v1beta1

---

README.md

This is to catch the case where users find-replace the `default` namespace with another namespace (say, `goldpinger` but don't change it for the ServiceAccount definition.
*Issue number of the reported bug or feature request: #<number>*
Added a `namespace` key under `metadata` with corresponding namespace (`default`) used elsewhere in the sample yaml.
Tested on prem, k8s 1.27 with `kubectl apply -f file.yaml`.
N/A.

Add default namespace `default` to ServiceAccount definition in example yaml
